"""
EduPro Demographics — Email Scheduler Module
==============================================
Handles composing, scheduling, and sending automated report emails.
Supports demo mode (saves to disk) and live SMTP mode.
"""

import smtplib
import io
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from typing import Optional

from loguru import logger

from src.config import (
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD,
    EMAIL_FROM, EMAIL_DEMO_MODE, EMAILS_DIR,
)


# ══════════════════════════════════════════════
# Email Composition
# ══════════════════════════════════════════════
def compose_report_email(
    recipients: list[str],
    subject: str,
    body_text: str,
    report_attachment: Optional[bytes] = None,
    attachment_name: str = "edupro_report.txt",
) -> MIMEMultipart:
    """
    Compose an email with optional report attachment.

    Parameters
    ----------
    recipients : list[str]
        Email recipient addresses.
    subject : str
        Email subject line.
    body_text : str
        Email body content.
    report_attachment : bytes, optional
        Report file content to attach.
    attachment_name : str
        Filename for the attachment.

    Returns
    -------
    MIMEMultipart
        Composed email message.
    """
    msg = MIMEMultipart()
    msg["From"] = EMAIL_FROM
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject
    msg["Date"] = datetime.now().strftime("%a, %d %b %Y %H:%M:%S +0000")

    # HTML body
    html_body = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #333; }}
            .header {{ background: linear-gradient(135deg, #6C63FF, #FF6584);
                       padding: 20px; text-align: center; border-radius: 8px; }}
            .header h1 {{ color: white; margin: 0; font-size: 24px; }}
            .content {{ padding: 20px; background: #f9f9f9; border-radius: 8px;
                        margin-top: 15px; }}
            .footer {{ text-align: center; padding: 15px; color: #999; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🎓 EduPro Demographics Report</h1>
        </div>
        <div class="content">
            {body_text.replace(chr(10), '<br>')}
        </div>
        <div class="footer">
            <p>This report was auto-generated by EduPro Analytics on
               {datetime.now().strftime('%B %d, %Y at %I:%M %p')}.</p>
            <p>© 2026 EduPro Analytics Team</p>
        </div>
    </body>
    </html>
    """
    msg.attach(MIMEText(html_body, "html"))

    # Attachment
    if report_attachment:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(report_attachment)
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={attachment_name}",
        )
        msg.attach(part)

    return msg


# ══════════════════════════════════════════════
# Email Sending
# ══════════════════════════════════════════════
def send_email(msg: MIMEMultipart) -> tuple[bool, str]:
    """
    Send an email via SMTP or save to disk in demo mode.

    Returns
    -------
    tuple[bool, str]
        (success, message)
    """
    if EMAIL_DEMO_MODE:
        return _save_demo_email(msg)
    return _send_smtp_email(msg)


def _send_smtp_email(msg: MIMEMultipart) -> tuple[bool, str]:
    """Send email via configured SMTP server."""
    if not SMTP_USER or not SMTP_PASSWORD:
        return False, "SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD environment variables."

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
        logger.success(f"Email sent to: {msg['To']}")
        return True, f"Email sent successfully to {msg['To']}"
    except Exception as exc:
        logger.error(f"Failed to send email: {exc}")
        return False, f"Failed to send email: {exc}"


def _save_demo_email(msg: MIMEMultipart) -> tuple[bool, str]:
    """Save email to disk in demo mode instead of sending."""
    try:
        EMAILS_DIR.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"report_email_{timestamp}.eml"
        filepath = EMAILS_DIR / filename
        filepath.write_text(msg.as_string(), encoding="utf-8")
        logger.success(f"Demo email saved to: {filepath}")
        return True, f"Demo mode: Email saved to {filepath}"
    except Exception as exc:
        logger.error(f"Failed to save demo email: {exc}")
        return False, f"Failed to save demo email: {exc}"


# ══════════════════════════════════════════════
# Email Templates
# ══════════════════════════════════════════════
def create_daily_summary_email(
    recipients: list[str],
    kpis: dict,
    report_text: Optional[str] = None,
    pdf_bytes: Optional[bytes] = None,
) -> MIMEMultipart:
    """Create a daily summary report email."""
    subject = f"📊 EduPro Daily Report — {datetime.now().strftime('%B %d, %Y')}"

    body = f"""
    <h2>📊 Daily Analytics Summary</h2>

    <table style="border-collapse: collapse; width: 100%;">
        <tr style="background: #6C63FF; color: white;">
            <th style="padding: 10px; text-align: left;">Metric</th>
            <th style="padding: 10px; text-align: right;">Value</th>
        </tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">Total Learners</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">{kpis.get('total_learners', 'N/A'):,}</td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">Average Age</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">{kpis.get('average_age', 'N/A')}</td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">Male / Female</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">{kpis.get('male_count', 0):,} / {kpis.get('female_count', 0):,}</td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #eee;">Gender Ratio</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">{kpis.get('gender_ratio', 'N/A')}</td></tr>
        <tr><td style="padding: 8px;">Top Email Provider</td>
            <td style="padding: 8px; text-align: right;">{kpis.get('most_common_provider', 'N/A')}</td></tr>
    </table>
    """

    attachment = None
    attachment_name = "edupro_report.txt"

    if pdf_bytes:
        attachment = pdf_bytes
        attachment_name = f"edupro_report_{datetime.now().strftime('%Y%m%d')}.pdf"
    elif report_text:
        attachment = report_text.encode("utf-8")
        attachment_name = f"edupro_report_{datetime.now().strftime('%Y%m%d')}.txt"

    return compose_report_email(
        recipients=recipients,
        subject=subject,
        body_text=body,
        report_attachment=attachment,
        attachment_name=attachment_name,
    )


def get_schedule_options() -> list[dict]:
    """Return available schedule frequency options."""
    return [
        {"label": "Daily (8:00 AM)", "cron": "0 8 * * *", "description": "Every day at 8:00 AM"},
        {"label": "Weekly (Monday 8:00 AM)", "cron": "0 8 * * 1", "description": "Every Monday at 8:00 AM"},
        {"label": "Monthly (1st, 8:00 AM)", "cron": "0 8 1 * *", "description": "1st of every month at 8:00 AM"},
        {"label": "Quarterly", "cron": "0 8 1 1,4,7,10 *", "description": "1st of every quarter at 8:00 AM"},
    ]
